<?xml version="1.0"?>
<robot name="basic_xacro"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="height1" value="2" />
    <xacro:property name="mass" value="1" />
    <xacro:property name="width" value="0.1" />

    <material name="orange">
        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
      </material>

    <link name="world"/>

    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="link1"/>
    </joint>

    <!-- Base Link -->
    <link name="link1">
        <collision>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height1}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height1}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <inertial>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <mass value="${mass}"/>
            <inertia ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0" iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0" izz="${mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
    </link>
</robot>